// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible", Justification = "<Pending>", Scope = "member", Target = "~M:GFX.Tutorial.Windows.User32.FindWindowEx(System.IntPtr,System.IntPtr,System.String,System.String)~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible", Justification = "<Pending>", Scope = "member", Target = "~M:GFX.Tutorial.Windows.User32.ClientToScreen(System.IntPtr,GFX.Tutorial.Windows.POINT@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible", Justification = "<Pending>", Scope = "member", Target = "~M:GFX.Tutorial.Windows.User32.GetClassName(System.IntPtr,System.Text.StringBuilder,System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible", Justification = "<Pending>", Scope = "member", Target = "~M:GFX.Tutorial.Windows.User32.GetClientRect(System.IntPtr,GFX.Tutorial.Windows.RECT@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible", Justification = "<Pending>", Scope = "member", Target = "~M:GFX.Tutorial.Windows.User32.GetParent(System.IntPtr)~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible", Justification = "<Pending>", Scope = "member", Target = "~M:GFX.Tutorial.Windows.User32.GetWindowRect(System.IntPtr,GFX.Tutorial.Windows.RECT@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible", Justification = "<Pending>", Scope = "member", Target = "~M:GFX.Tutorial.Windows.User32.GetWindowText(System.IntPtr,System.Text.StringBuilder,System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible", Justification = "<Pending>", Scope = "member", Target = "~M:GFX.Tutorial.Windows.User32.IsWindowVisible(System.IntPtr)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible", Justification = "<Pending>", Scope = "member", Target = "~M:GFX.Tutorial.Windows.User32.SendMessage(System.IntPtr,System.Int32,System.IntPtr,System.IntPtr)~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible", Justification = "<Pending>", Scope = "member", Target = "~M:GFX.Tutorial.Windows.User32.SendMessage(System.IntPtr,System.Int32,System.IntPtr,System.Text.StringBuilder)~System.IntPtr")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible", Justification = "<Pending>", Scope = "member", Target = "~M:GFX.Tutorial.Windows.User32.MoveWindow(System.IntPtr,System.Int32,System.Int32,System.Int32,System.Int32,System.Boolean)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "<Pending>", Scope = "member", Target = "~M:GFX.Tutorial.Engine.Render.RenderHost.Dispose")]
